- README.md
- ecdsa/__init__.py
- ecdsa/curves.py
- ecdsa/der.py
- ecdsa/ecdsa.py
- ecdsa/ellipticcurve.py
- ecdsa/keys.py
- ecdsa/numbertheory.py
- ecdsa/rfc6979.py
- ecdsa/test_pyecdsa.py
- ecdsa/util.py
Used the `pep8` tool, with `--ignore=E111,E114,E501,E121,E502` to make the code base more PEP8 compliant. This change should only be about whitespace and in the case of `__init__.py`.also some ordering of the code (to comply with PEP8 guidelines).
This doesn't address `_version.py` and `six.py` as I assume these to be external.
> PEP8 compliance, whitespace only

- .coveragerc
- .travis.yml
- build-requirements-3.3.txt
- build-requirements.txt
- tox.ini
because the code moved to `src` directory, the old `coverage` includes/excludes became obsoleted, fix this
also include branch coverage in collection
fixes #83
> Coverage fix

- src/ecdsa/ecdsa.py
- src/ecdsa/keys.py
- src/ecdsa/rfc6979.py
As per rfc6979:
> If that value of k is within the [1,q-1] range, **and is**
> **suitable for DSA or ECDSA (i.e., it results in an r value**
> **that is not 0; see Section 3.4)**, then the generation of k is
> finished. The obtained value of k is used in DSA or ECDSA.
> Otherwise, compute:
` k is within the [1,q-1] range` is being checked, but the part about r and s values aren't 0 is not currently being checked.
In the event a sig with 0 as the r or s value is leaked, the private key is easily calculated.
(Though this is extremely rare, this PR is for correctness sake)
> Make sure that r and s don't become 0

- src/ecdsa/keys.py
- src/ecdsa/rfc6979.py
```
Additional data may be added to the input of HMAC, concatenated
after bits2octets(H(m)):
K = HMAC_K(V || 0x00 || int2octets(x) || bits2octets(h1) || k')
```
Also follows implementation in secp256k1 library:
https://github.com/bitcoin-core/secp256k1/blob/452d8e4d2a2f9f1b5be6b02e18f1ba102e5ca0b4/src/secp256k1.c#L332
Recently, Bitcoin Core merged a feature that utilizes this feature in the secp256k1 library.
Eventually, Electrum (which depends on this library) may implement it, so would like to lay the ground work.
> Add ability to include additional data as per RFC6979 section 3.6

- setup.py
Set `long_description_content_type='text/markdown'` in `setup.py`. I believe this should trigger the README to display with proper formatting on [PyPI](https://pypi.org/project/ecdsa/). Currently, PyPI looks like:
Refs https://packaging.python.org/tutorials/distributing-packages/#description and https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi.
> Specify markdown README for PyPI's long_description

- README.md
TypeError: Unicode-objects must be encoded before hashing
> Add encoding for Unicode to prevent TypeError

- src/ecdsa/ecdsa.py
- src/ecdsa/keys.py
- src/ecdsa/test_ecdsa.py
- src/ecdsa/test_pyecdsa.py
Added methods and test for public key recovery.
fixes #101
> Pk Recovery

- build-requirements-2.6.txt
PyYAML dropped support for 2.6
> downgrade requirements on py2.6

- build-requirements-3.3.txt
- src/ecdsa/keys.py
Fixed the issue that keys.py#Line89 using the wrong parameter
Downgrade `pluggy` to **0.5.2** while using Python33, so it can install `tox` successfully.
> To fix issue #108

- .travis.yml
- build-requirements-2.6.txt
- src/ecdsa/der.py
- src/ecdsa/keys.py
- src/ecdsa/test_der.py
- src/ecdsa/test_malformed_sigs.py
- src/ecdsa/util.py
- tox.ini
Ensure that the signature verification raises the same exception irrespective if the error is caused by mismatch of the hash value or because the encoding of the signature is invalid
fixes #114
> Robust signature decoding

- src/ecdsa/keys.py
- src/ecdsa/test_pyecdsa.py
the call to klass.from_public_key_recovery_with_digest()
used the hardcoded sha1, effectively ignoring the hashfunc passed
as the paramter to from_public_key_recovery()
also use the canonical name of first parameter in classmethods
> Fix wrong func in from_public_key_recovery()

- src/ecdsa/keys.py
- src/ecdsa/numbertheory.py
- src/ecdsa/test_pyecdsa.py
This is re-working of the PR #54 (which in turn is a reworking of #34).
This implements support for the compressed, uncompressed and hybrid format specified in X9.62 and the SEC1 standards
http://www.secg.org/sec1-v2.pdf
fixes #1, #53 
closes #54, #34 
I'm not adding documentation as I plan to do that either in #117 or after #117 is merged
> Support for X9.62 formatted public keys

- src/ecdsa/keys.py
MalformedPointError can be raised by public methods, so it should get
imported with "*"
> add MalformedPointError to __all__

- .coveragerc
- .travis.yml
- README.md
- build-requirements-2.6.txt
- build-requirements-3.2.txt
- build-requirements-3.3.txt
- build-requirements.txt
- ecdsa/__init__.py
- ecdsa/der.py
- ecdsa/keys.py
- ecdsa/test_der.py
- ecdsa/test_malformed_sigs.py
- ecdsa/test_pyecdsa.py
- ecdsa/util.py
- tox.ini
Backport the recent fixes to signature decoding.
See #114 
also harden the public and private key decoding (partial backport of #118)
> Backport signature decode

- README.md
since the parsers now raise predictable exceptions, do document
what are they
> document exceptions in from_* methods

- NEWS
keep the NEWS file up to date compared to 0.13 branch
> uplift NEWS from 0.13 branch

- src/ecdsa/curves.py
- src/ecdsa/ecdsa.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/rfc6979.py
- src/ecdsa/util.py
This should be a mitigation for the Minerva attack. See https://minerva.crocs.fi.muni.cz for more info.
> Apply nonce bit-length mitigation to stop timing leakage.

- .coveragerc
- README.md
- src/ecdsa/__init__.py
- src/ecdsa/keys.py
- src/ecdsa/numbertheory.py
- src/ecdsa/test_pyecdsa.py
Uplift the test coverage from #124 to master
deprecate some unused methods
clean-up raised exceptions
> More test coverage

- .travis.yml
- README.md
Designate pypy and pypy3 execution environments as official.
fixes #98
> make pypy and pypy3 support official

- src/ecdsa/keys.py
- src/ecdsa/test_pyecdsa.py
when encoding in ASN.1 the public point has to use uncompressed,
compressed or hybrid representation, raw is not allowed
so disallow it in API
fixes #136
> don't allow for creation of malformed DER files

- src/ecdsa/der.py
- src/ecdsa/keys.py
- src/ecdsa/test_der.py
- src/ecdsa/test_pyecdsa.py
the first byte of the bit string in DER is the number of unused bits in the bit string, parse it properly and give expected error values if the parsing fails
fixes #120 
Todo:
> Correct handling of BIT STRING in DER

- src/ecdsa/keys.py
- src/ecdsa/util.py
Document the VerifyingKey, SigningKey and few directly related classes.
fixes #56 
work towards #95
> Provide documentation for VerifyingKey and SigningKey

- .travis.yml
- README.md
- diff-instrumental.py
Add a Travis run that checks [condition coverage](https://en.wikipedia.org/wiki/Code_coverage#Basic_coverage_criteria) of the pull request.
partially addresses #131
> Add condition coverage

- .travis.yml
- src/ecdsa/_compat.py
- src/ecdsa/der.py
- src/ecdsa/keys.py
- src/ecdsa/rfc6979.py
- src/ecdsa/test_der.py
- src/ecdsa/test_keys.py
- src/ecdsa/util.py
Test for and fix the bugs in handling bytes-like objects in `VerifyingKey` and `SigningKey`.
fixes #135 
fixes #144
> Bytes-like object support

- .gitignore
- .travis.yml
- build-requirements-2.6.txt
- build-requirements-3.3.txt
- build-requirements.txt
- src/ecdsa/curves.py
- src/ecdsa/der.py
- src/ecdsa/keys.py
- src/ecdsa/test_malformed_sigs.py
- tox.ini
Start using hypothesis, use it for testing the slowest test case
fixes #130
> testing with hypothesis

- src/ecdsa/test_malformed_sigs.py
in case all the bytes of the signature were removed, there are
no bytes to change, so the selection of which bytes to change fails
run that code only if there is anything left of the old signature
> fix st_fuzzed_sig

- README.md
- src/ecdsa/keys.py
- src/ecdsa/numbertheory.py
- src/ecdsa/test_numbertheory.py
Minor speed-up from not performing the same operations twice and slight micro-opimisation
of inverse_mod (from #127)
depends on #146 and #145
> Minor speed-up

- src/ecdsa/der.py
- src/ecdsa/test_der.py
- src/ecdsa/test_malformed_sigs.py
- src/ecdsa/test_pyecdsa.py
make the code handle oids with a large second subidentifier (fixes #155)
make the code raise correct exception when the encoded multi-byte
subidentifier is missing the last byte
move OID test coverage to test_der module and extend it
update the OID generators in random DER generator to generate OIDs with
large second subidentifier
> der: fix encoding and decoding OIDs

- speed.py
> also include speed of ECDH in speed.py

- .travis.yml
- setup.py
- tox.ini
since we use features introduced in 1.9.0, we require it for
installation/use
> six: expect specific version

- src/ecdsa/util.py
rebase and fix minor issues from PR #37 
closes #37
> Bitwise randrange

- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_ellipticcurve.py
Revert an unfortunate consequence of 79d7d90 making CurveFp unhashable.
Fixes #172.
> make CurveFp hash()able again

- src/ecdsa/keys.py
- src/ecdsa/test_pyecdsa.py
- tox.ini
> Large hashes with small curves

- src/ecdsa/keys.py
- src/ecdsa/test_keys.py
All the other methods for creating the keys (both Signing and Verifying)
allow setting the default_hashfunc, add the parameter to the last
two of them
also a bit of whitespace cleanup
fixes #72
> support for setting hashfunc on verifying key load

- README.md
describe precompute option for keys
fixes #173
> document precompute

- src/ecdsa/_rwlock.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_rw_lock.py
> make scale() thread-safe

- build-requirements-2.6.txt
- build-requirements-3.3.txt
- build-requirements-3.4.txt
- build-requirements.txt
- tox.ini
freeze dependencies on Python 3.4
> depend on pyyaml working on py3.4

- src/ecdsa/keys.py
- src/ecdsa/numbertheory.py
- src/ecdsa/util.py
It's generally safer to compare to the `sys.version_info` tuple than the `sys.version` string, which can include assumptions that each version component is always a single character.
---
There's also some code which uses `six.PY3`, similar to:
```python
if six.PY3:
print("Python 3+ code")
else:
print "Python 2 code" 
```
Where:
```python
PY3 = sys.version_info[0] == 3
```
When run on Python 4, this will run the Python 2 code!
Instead, use `six.PY2`.
---
Found with https://github.com/asottile/flake8-2020.
> Fix for Python 3.10, 4 and 10

- src/ecdsa/keys.py
```python
>>> import ecdsa
>>> private_key = ecdsa.SigningKey.generate(curve=ecdsa.NIST256p)
>>> pub_key_pem_bytes = private_key.get_verifying_key().to_pem()
>>> type(pub_key_pem_bytes)
<class 'bytes'>
```
> Fix Return Type For to_pem 

- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_keys.py
> handle private keys equal to n-1

- src/ecdsa/rfc6979.py
> fix rounding on python3

- src/ecdsa/der.py
- src/ecdsa/keys.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_pyecdsa.py
- src/ecdsa/util.py
> Add support for PKCS#8 private keys

- src/ecdsa/test_rw_lock.py
Removes warnings such as this:
```
src/ecdsa/test_rw_lock.py::RWLockTestCase::test_many_writers_priority
/home/travis/build/warner/python-ecdsa/src/ecdsa/test_rw_lock.py:157: DeprecationWarning: Please use assertTrue instead.
self.assert_(threads[0].exit_time < threads[1].entry_time)
```
> switch from deprecated assert_ to assertTrue

- .travis.yml
xenial uses OpenSSL 1.0.2, it doesn't support `pkey -derive` significantly
reducing our test coverage for ECDH
> use bionic to get OpenSSL 1.1.1

- src/ecdsa/keys.py
- src/ecdsa/test_pyecdsa.py
PR #168 added the `allow_truncate` option to `SigningKey.sign_digest()` and `VerifyingKey.verify_digest()`, and then forcibly defaulted their value to `True` in [`SigningKey.sign()`](https://github.com/warner/python-ecdsa/pull/168/files#diff-a6539daf3a35718bc7cb90c1395b6953R1138) and [`VerifyingKey.verify()`](https://github.com/warner/python-ecdsa/pull/168/files#diff-a6539daf3a35718bc7cb90c1395b6953R602):
```python
class VerifyingKey(object):
...
def verify(self, signature, data, hashfunc=None,
sigdecode=sigdecode_string):
...
return self.verify_digest(signature, digest, sigdecode, True)
```
```python
class SigningKey(object):
def sign(self, data, entropy=None, hashfunc=None,
sigencode=sigencode_string, k=None):
return self.sign_digest(h, entropy, sigencode, k, allow_truncate=True)
``` …
> Expose allow_truncate option in SigningKey.sign() and VerifyingKey.verify()

- .gitignore
- src/ecdsa/__init__.py
- src/ecdsa/ellipticcurve.py
- tox.ini
this is an attempt to fix https://github.com/warner/python-ecdsa/issues/180
the does not change any existing behavior, but adds new behavior:
when `PYTHON_ECDSA_ENABLE_LAZY_PRECOMPUTE` env var is set, the multiplication tables for curves are only precomputed upon first use.
without the env var being set (the current behavior), tables for _all_ supported curves are precomputed at import time regardless of whether the curves are used in the user app at all. 
effect can be seen in this test:
```
(cpy382_2) oberstet@intel-nuci7:~/scm/3rdparty/python-ecdsa$ python test.py 
python-ecdsa v0.16.0+1.g3388afc
0.4552568449998944
(cpy382_2) oberstet@intel-nuci7:~/scm/3rdparty/python-ecdsa$ PYTHON_ECDSA_ENABLE_LAZY_PRECOMPUTE=1 python test.py 
python-ecdsa v0.16.0+1.g3388afc
0.020854599999438506 …
```
> add option to lazily precompute multiplication tables

- src/ecdsa/keys.py
all curves we have defined, with exception of NIST P-521, have
bit length of order that's multiple of 8, and there are no hashes
that are longer than 512 bits, so NIST P-521 is not affected either,
but do fix this issue in case user provides raw input longer than
512 bits or uses custom curves
fix #197
> fix truncation of hash input with order bit size not multiple of 8

- src/ecdsa/keys.py
> Fix docstring in keys.py: RFC6697 should be RFC6979

- src/ecdsa/_compat.py
- src/ecdsa/der.py
- src/ecdsa/test_ecdh.py
- src/ecdsa/util.py
- tox.ini
coveralls complains about branches that are executed in one environment only, but if they are version specific, that's expected
so try excluding them
> Exclude version specific coverage

- README.md
be more explicit about ecdh support in readme,
make the History flow better
> refresh readme contents

- README.md
- speed.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_jacobi.py
- tox.ini
- include verification of signatures with no precomputed point multiples in `speed.py` report
- speed up the signature verify operation by using NAF in the `mul_add()` method by about 4-5%
> Speed up single-shot verify

- README.md
- src/ecdsa/numbertheory.py
the builtin pow() can handle negative powers on python 3.8 and later,
so do use it
> use native inverse modulo when available

- .travis.yml
- src/ecdsa/test_ecdh.py
#127 is now merged so let's try enabling the `test_malformed_sigs.py` test
> speed up instrumental, reenable test_malformed_sigs.py under it

- .travis.yml
- src/ecdsa/__init__.py
- src/ecdsa/curves.py
- src/ecdsa/ecdh.py
- src/ecdsa/ecdsa.py
- src/ecdsa/keys.py
- src/ecdsa/numbertheory.py
- src/ecdsa/test_ecdh.py
- src/ecdsa/test_jacobi.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_numbertheory.py
- src/ecdsa/test_pyecdsa.py
- tox.ini
finish fixing #197, fix #224 
fix #24 
because we deduplicate some fairly well-tested code, the overall percentage coverage of `ecdsa.keys` _falls_, making straight-up change fail instrumental testing; add some test coverage for it to counteract it
also adds some static test coverage for `is_prime()` to stop the line coverage fluctuating based on hypothesis choices
> Add support for small curves

- README.md
- setup.py
- src/ecdsa/__init__.py
- src/ecdsa/numbertheory.py
Adjust links after migration to tlsfuzzer organisation and migration from Travis-CI.org to Travis-CI.com
fixes #226
> update URIs and badges after migration to tlsfuzzer org

- src/ecdsa/ecdsa.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/keys.py
- src/ecdsa/test_der.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_pyecdsa.py
fixes #227 
on python2 `__ne__` needs to be implemented for every `__eq__` defined, otherwise `assertNotEqual` and reflection doesn't work
> Fix (in)equality tests

- src/ecdsa/__init__.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/numbertheory.py
- src/ecdsa/test_der.py
- src/ecdsa/test_ecdh.py
- src/ecdsa/test_ellipticcurve.py
- src/ecdsa/test_jacobi.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_malformed_sigs.py
- src/ecdsa/test_numbertheory.py
- src/ecdsa/test_pyecdsa.py
remove unused imports, bad assert methods, unused variables etc.
> fix LGTM alerts

- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_jacobi.py
- src/ecdsa/test_rw_lock.py
since both __coords and __precompute have a "final" state, we can easily
implement lock-less handling of those parameters by depending on GIL
(the atomicity of single bytecode instructions)
fixes #238
closes #239 (this in an alternative, simpler approach)
> implement lock-less algorithm in PointJacobi

- src/ecdsa/ecdh.py
- src/ecdsa/keys.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_pyecdsa.py
Allow specifying what point formats are supported when loading public
keys. Limit the point formats when loading PEM and DER public files
to the formats actually allowed in them: uncompressed, compressed,
and hybrid. Previous code would allow raw encoding too.
fixes #214
> allow limiting point formats, don't accept malformed PEM public files

- build-requirements-3.4.txt
- src/ecdsa/curves.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/errors.py
- src/ecdsa/keys.py
- src/ecdsa/test_curves.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_pyecdsa.py
- tox.ini
Add support for reading and writing curve parameters.
TODO:
fixes #39
> Support explicit curve params

- .github/workflows/ci.yml
- src/ecdsa/_compat.py
- src/ecdsa/_sha3.py
- src/ecdsa/test_sha3.py
On earlier pythons we don't have the ability to set the size of
SHAKE-256 output, so we need to use our own implementation.
Context: #256
> add SHAKE-256 implementation

- src/ecdsa/ellipticcurve.py
- src/ecdsa/numbertheory.py
- src/ecdsa/test_malformed_sigs.py
- versioneer.py
There are small typos in:
- src/ecdsa/ellipticcurve.py
- src/ecdsa/numbertheory.py
- src/ecdsa/test_malformed_sigs.py
- versioneer.py
Fixes:
- Should read `support` rather than `suport`.
- Should read `languages` rather than `langauges`.
- Should read `internally` rather than `interanlly`.
- Should read `arbitrarily` rather than `arbitrarly`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- src/ecdsa/ecdsa.py
While it's natural to look at the ecdsa module, users shouldn't use it to implement ECDSA in their applications, add a note redirecting them to the appropriate keys module.
See also #95
> add note to not use low level interfaces

- src/ecdsa/keys.py
- src/ecdsa/test_keys.py
Try to fix #280. 
[RFC5958](https://datatracker.ietf.org/doc/html/rfc5958#section-2) shows that pkcs8 v2 has the format:
```
OneAsymmetricKey ::= SEQUENCE {
version                   Version,
privateKeyAlgorithm       PrivateKeyAlgorithmIdentifier,
privateKey                PrivateKey,
attributes            [0] Attributes OPTIONAL,
...,
[[2: publicKey        [1] PublicKey OPTIONAL ]],
...
}
```
There are maybe optional Attributes and Publickey after Privatekey.  Thus it may not raise error when there are trailing data.
> try to support pkcs8 v2 format pem file for EdDSA

- src/ecdsa/_compat.py
- src/ecdsa/test_keys.py
Python 3.3 refuses to cast an empty byte string back to bytes, so return an empty byte string manually.
> workaround py3.3 bug with empty strings and memoryview

- README.md
Hey! I was looking for an ECDSA library for my python application and this came up as the first option. It was not super apparent that it is _not intended for production_ use (i.e. it is vulnerable to side channel attacks) and I thought it warranted mentioning this up front. 
I want to be clear, I really appreciate that this library walks through the signing algorithms in an easy-to-understand manner and is much friendlier that staring at C implementations 😄!
> [Docs] Add warning that this is not intended for production use

- src/ecdsa/keys.py
* fix the documentation to list the two valid encoding formats
* Allow the user to control the encoding format of the curve generator when exporting public key with explicit parameters
> explicit curve encoding fixes

- src/ecdsa/ellipticcurve.py
- src/ecdsa/numbertheory.py
- src/ecdsa/test_numbertheory.py
Since explicit curve parameters may not use prime numbers as the field
(see CVE-2022-0778), make sure that our square_root_mod_prime()
handles non-prime p gracefully
> better handling for malformed curve parameters

- docs/Makefile
- docs/make.bat
- docs/source/conf.py
- docs/source/ecdsa.curves.rst
- docs/source/ecdsa.der.rst
- docs/source/ecdsa.ecdh.rst
- docs/source/ecdsa.ecdsa.rst
- docs/source/ecdsa.ellipticcurve.rst
- docs/source/ecdsa.errors.rst
- docs/source/ecdsa.keys.rst
- docs/source/ecdsa.numbertheory.rst
- docs/source/ecdsa.rfc6979.rst
- docs/source/ecdsa.rst
- docs/source/ecdsa.util.rst
- docs/source/index.rst
- docs/source/modules.rst
- src/ecdsa/_compat.py
- src/ecdsa/ecdh.py
- src/ecdsa/ecdsa.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/keys.py
- src/ecdsa/rfc6979.py
Fix up documentation so that Sphinx can actually build it, add a basic skeleton of pages.
Adds just autogenerated API documentation for now.
Work towards #95
> Doc generation

- .github/workflows/ci.yml
- src/ecdsa/test_keys.py
- src/ecdsa/test_malformed_sigs.py
- src/ecdsa/test_pyecdsa.py
Add support for EdDSA signatures (Ed25519 and Ed448).
Todo:
> EdDSA support

- src/ecdsa/curves.py
- src/ecdsa/test_curves.py
Given that curves have two names (the python-ecdsa name and the optional openssl name), finding a curve by name is non-trivial.
Add a helper function for finding curves by name.
Also document the helper function that finds curve by OID
> Selecting curve by name

- .github/workflows/ci.yml
actions deprecated the python version that's natively included in the supported Ubuntu-20.04, so just use the native version...
> fix CI for python2.7

- src/ecdsa/der.py
- src/ecdsa/keys.py
- src/ecdsa/ssh.py
- src/ecdsa/test_keys.py
Initial support for exporting keys in the SSH format as requested in #111.
For now it only supports Ed25519 curves but it shouldn't be hard to add additional ones.
> export to ssh

- .github/workflows/ci.yml
- .travis.yml
- README.md
- conftest.py
- cosmic-ray-12way.sh
- cosmic-ray-12way.toml
- cosmic-ray.sh
- cosmic-ray.toml
- sql/combine.sql
- sql/create_to_del.sql
- sql/shard-db.sql
- src/ecdsa/ecdsa.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_der.py
- src/ecdsa/test_ecdh.py
- src/ecdsa/test_ecdsa.py
- src/ecdsa/test_eddsa.py
- src/ecdsa/test_ellipticcurve.py
- src/ecdsa/test_jacobi.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_malformed_sigs.py
- src/ecdsa/test_numbertheory.py
- src/ecdsa/test_pyecdsa.py
> Introduce mutation testing

- speed.py
- src/ecdsa/der.py
- src/ecdsa/ecdsa.py
- src/ecdsa/keys.py
- src/ecdsa/test_der.py
- src/ecdsa/test_jacobi.py
- src/ecdsa/test_pyecdsa.py
- src/ecdsa/util.py
as a side effect the program would maybe run faster
> remove usage of six.b("literal")

- .github/workflows/ci.yml
- cosmic-ray-12way.toml
- cosmic-ray.toml
- src/ecdsa/ellipticcurve.py
- src/ecdsa/keys.py
- src/ecdsa/numbertheory.py
- src/ecdsa/test_ecdh.py
- src/ecdsa/test_eddsa.py
- src/ecdsa/test_ellipticcurve.py
- src/ecdsa/test_jacobi.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_malformed_sigs.py
- src/ecdsa/test_numbertheory.py
- src/ecdsa/test_sha3.py
related to #131 
0.14.1: With just 20 mutants executed in 25 minutes, it's not really useful (the confidence interval is way too large)
0.15-beta (8deb089e7d): Single test suite execution takes about 9.97s on Travis, in 25 minutes we execute 107 tests, so better, but that still translates to a 99.9% confidence interval of 5.39% to 26.38% for survival rate. So we will need a faster test suite still.
0.16.0: No significant change, about 152 tests in 25 minutes, 
todo:
> Add mutation testing to CI

- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_ellipticcurve.py
- src/ecdsa/test_jacobi.py
- src/ecdsa/test_pyecdsa.py
when the order of the curve is not a prime, then point doubling can return INFINITY, this will cause some negative values not to be reduced modulo curve p; fix this
fixes #343
> handle non-prime order curves more gracefully

- src/ecdsa/der.py
- src/ecdsa/test_der.py
While not needed for ECDSA/ECDH PKCS#8 files, it looks like it will be necessary for the PQC algorithms, so provide that too, so we can do some code reuse.
> add support for parsing implicit DER tags

- src/ecdsa/test_pyecdsa.py
- src/ecdsa/util.py
> use integer division for canonicalization of signatures
