- src/ecdsa/rfc6979.py
remove code that is not used any more (needed for Python 2.5 compatibility)
> Dead code removal

- README.md
> update docs after test suite changes

- src/ecdsa/test_pyecdsa.py
> check if system openssl supports a curve before running test

- src/ecdsa/numbertheory.py
> Use math.gcd if available

- src/ecdsa/test_ellipticcurve.py
update the test coverage for the ellipticcurve module too
> Ellipticcurve tests

- src/ecdsa/test_malformed_sigs.py
- src/ecdsa/test_numbertheory.py
fix unstable st_der() and more test coverage for numbertheory
> Little more test coverage

- src/ecdsa/keys.py
SigningKey.from_der - returns SigningKey
SigningKey.from_pem - returns SigningKey
> fix rtype for SigningKey factory methods docstrings

- build-requirements-3.3.txt
> fix submission of results to coveralls on Py3.3

- .travis.yml
we have no platform specific code so the code and tests should just run on Windows
> enable CI on Windows

- src/ecdsa/keys.py
- src/ecdsa/test_jacobi.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_numbertheory.py
- src/ecdsa/test_pyecdsa.py
add test coverage to stabilise coverage and improve some condition coverage
> More test coverage

- src/ecdsa/test_ecdsa.py
hypothesis is still making the coverage fluctuate so add few tests that verify handling of special cases
> test coverage for ecdsa module

- .github/workflows/ci.yml
- build-requirements-2.6.txt
- build-requirements-2.7.txt
- build-requirements-3.3.txt
- build-requirements.txt
- tox.ini
Since Travis is no more, use Github Actions to run our tests, fixes #241
> use Github Actions for CI

- .github/workflows/ci.yml
add remaining test items from the old travis configuration
> More tests

- .github/workflows/ci.yml
also update location of py3.3 get-pip.py
> workaround non-SNI access to pip CDN

- src/ecdsa/eddsa.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_eddsa.py
To support EdDSA (#256) we need to have an implementation of point arithmetic over twisted Edwards curves.
> Add Twisted Edwards curve point arithmetic

- .gitignore
- src/ecdsa/_compat.py
- src/ecdsa/eddsa.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_eddsa.py
Add the low level implementation of EdDSA
context: #256
> Low level EdDSA

- .github/workflows/ci.yml
- speed.py
- src/ecdsa/__init__.py
- src/ecdsa/curves.py
- src/ecdsa/eddsa.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/keys.py
- src/ecdsa/test_curves.py
- src/ecdsa/test_ecdh.py
- src/ecdsa/test_eddsa.py
- src/ecdsa/test_keys.py
- src/ecdsa/test_malformed_sigs.py
- tox.ini
Add EdDSA support to SigningKey, VerifyingKey
Serialisation of them to PEM/PKCS#8 files
> High level API for EdDSA keys

- .github/workflows/ci.yml
as Actions deprecates 16.04 we need to migrate to 18.04
> use Ubuntu 18.04 for old pythons

- .github/workflows/ci.yml
- README.md
- diff-instrumental.py
Automatically update the condition coverage badge for the repo.
fixes #244
> add automatic condition coverage badge

- .github/workflows/ci.yml
- setup.py
> Add Python 3.11 to test matrix, update python 3.10 docs

- src/ecdsa/test_malformed_sigs.py
- src/ecdsa/test_pyecdsa.py
- src/ecdsa/util.py
More test coverage and docs for `utils` module
> More tests and docs

- .github/workflows/ci.yml
- src/ecdsa/__init__.py
- src/ecdsa/curves.py
- src/ecdsa/ecdsa.py
- src/ecdsa/test_pyecdsa.py
Add support for twisted variants of Brainpool curves
> add support for twisted Brainpool curves

- src/ecdsa/ellipticcurve.py
> Remove unnecessary adds from mul_add

- src/ecdsa/ecdsa.py
- src/ecdsa/ellipticcurve.py
- src/ecdsa/test_pyecdsa.py
here is a new patch to reduce patching in Debian while keeping here the package Python2.6 compatible
greetings
> trim more usage of six.b()

- src/ecdsa/ecdsa.py
> fix warning of int_to_string() and string_to_int()

- README.md
> use the new badge URL for the build status
